services:
  add-db:
    image: mysql:8.4.3
    platform: linux/arm64/v8
    command:
      --collation-server=utf8mb4_0900_bin
      --transaction-isolation=READ-COMMITTED
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 53306:3306
  frontend:
    build:
      context: app/frontend
      dockerfile: Dockerfile
    ports:
      - 18080:80
      - 3000:3000
    depends_on:
      - add-db
    volumes:
      - ./app/frontend:/app
    #tty: true # 起動した状態でコンテナに維持
    command: yarn dev
  backend:
    build:
      context: app/backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - add-db
    volumes:
      - ./app/backend:/app
    tty: true
    command: python manage.py runserver 0.0.0.0:8000 --settings config.settings.development

